/**
 * RESPONSIVE IMAGE HELPERS
 * Mercy - A Story Worth Celebrating
 *
 * Every photograph is served as a WebP size ladder (320 / 640 / 960) with a
 * progressive JPEG fallback. The ladder is generated by tools/optimize-images.py
 * and described by js/media-manifest.json, keyed by the ORIGINAL filename so the
 * existing markup and data registry keep working unchanged.
 *
 * Why this exists: the story renders dozens of photographs. Serving each one at
 * full resolution cost ~159KB every; the correct size averages ~42KB, and the
 * first-screen hero is ~12KB.
 *
 * This file must load before js/main.js.
 */
(function (global) {
  "use strict";

  var MANIFEST_URL = "js/media-manifest.json";
  var manifest = null;
  var lookup = Object.create(null);

  /** Strip a directory and query string, returning the bare original filename. */
  function baseName(src) {
    if (!src) return "";
    var clean = String(src).split("?")[0].split("#")[0];
    var parts = clean.split("/");
    return parts[parts.length - 1];
  }

  function findEntry(src) {
    if (!manifest) return null;
    return manifest[baseName(src)] || null;
  }

  /**
   * Build the attribute set for one photograph.
   *
   * @param {string} src        Original asset path (kept for the no-JS / no-JS
   *                            -manifest fallback).
   * @param {object} [options]
   * @param {string} [options.sizes]  The `sizes` hint, e.g. "(max-width: 640px) 92vw, 40vw".
   * @param {string} [options.className]
   * @param {boolean} [options.eager]   Fetch immediately (used only for the hero).
   * @param {string} [options.fetchPriority]
   * @returns {object} attributes to apply to an <img>.
   */
  function buildImageAttributes(src, options) {
    var opts = options || {};
    var entry = findEntry(src);
    var attrs = {
      src: src,
      alt: opts.alt || "",
      className: opts.className || "",
      loading: opts.eager ? "eager" : "lazy",
      decoding: "async"
    };

    if (!entry) return attrs;

    attrs.srcset = entry.widths.map(function (width) {
      return "assets/img/" + entry.slug + "-" + width + ".webp " + width + "w";
    }).join(", ");
    // The JPEG fallback stays in `src` for any browser without WebP support.
    attrs.src = entry.src;
    attrs.width = entry.width;
    attrs.height = entry.height;
    if (opts.sizes) attrs.sizes = opts.sizes;
    if (opts.eager) {
      attrs.loading = "eager";
      attrs.fetchPriority = opts.fetchPriority || "high";
    }
    return attrs;
  }

  /** Apply a built attribute set to an <img> element. */
  function applyImage(img, src, options) {
    if (!img) return img;
    var attrs = buildImageAttributes(src, options);
    Object.keys(attrs).forEach(function (key) {
      if (key === "className") {
        if (attrs.className) img.className = attrs.className;
        return;
      }
      if (key === "alt") {
        img.alt = attrs.alt;
        return;
      }
      if (attrs[key] === undefined || attrs[key] === null || attrs[key] === "") return;
      img.setAttribute(key, attrs[key]);
    });
    return img;
  }

  /** A poster path for a video, preferring a real extracted frame. */
  function posterFor(src, fallbackImage) {
    var entry = findEntry(src);
    if (entry && entry.poster) return entry.poster;
    return fallbackImage || null;
  }

  global.MERCY_MEDIA = {
    ready: false,
    load: function () {
      if (manifest) return Promise.resolve(manifest);
      return fetch(MANIFEST_URL, { cache: "no-cache" })
        .then(function (response) {
          if (!response.ok) throw new Error("manifest " + response.status);
          return response.json();
        })
        .then(function (data) {
          manifest = data || {};
          global.MERCY_MEDIA.ready = true;
          return manifest;
        })
        .catch(function () {
          // The story must never depend on this file: fall back to the original
          // photographs, which are still present in the repository.
          manifest = null;
          global.MERCY_MEDIA.ready = true;
          return null;
        });
    },
    entryFor: function (src) { return findEntry(src); },
    buildImageAttributes: buildImageAttributes,
    applyImage: applyImage,
    posterFor: posterFor
  };

  if (typeof document !== "undefined") {
    global.MERCY_MEDIA.load();
  }
})(window);
